### ISSUE TITLE
Makefile nodepth files missing(Viewer.cpp & Tiago.cpp)

### ISSUE THREAD

**Issue by niloferbano** [derzu/BodySkeletonTracker#3]
Hey Derzu,

We tried running your BodySkeletonTracker. We wanted to run the code for webcam, but Viewer.cpp and Tiago.cpp files are missing. Could you please point us to the locations of these files ? Is there any other way to get it executed. We used the depth makefile, but we don't have a depth camera.

Thanks,
Nilofer

**Comment by derzu** [comment]
Hi @niloferbano,

The Makefile.noDepth file was outdated, now I update, and it's compiling and running. I just commit the new version of the file Makefile.noDepth. 

Please give a "git pull" to update your repository version. And rename the Makefile.noDepth to Makefile.

Note that the "No Depth Mode" just works if you have a white and smooth background.

Best regards,

Derzu.

**Comment by derzu** [comment]
Does it now compile successfully?

**Comment by niloferbano** [comment]
Hello @derzu,

Thank you so much for your reply. Yes, its working. I could also make it run my editing the CFLAG in depth Makefile. I was getting some compiler error, so I had to comment out lines in the code and which I guess this is why I am not getting desired output. 

Thanks,
Nilofer

**Comment by derzu** [comment]
Great! If you wanna any help with the compile errors from the lines that you comment, let me know.

Best regards,

Derzu.

**Comment by niloferbano** [comment]
Hello Derzu,

Thanks for your reply. I am new to Opencv programming. I could not fix the issue which is why I commented out the lines.

I commented line numbers 464 and 465 in file src/Skeleton.cpp to get rid of the errors. 
And it seems like, because of this I am not getting expected output.

Error:
/usr/include/opencv2/core/mat.hpp:1571:12: note:   template argument deduction/substitution failed:
src/Skeleton.cpp:465:5: note:   ‘cv::Point’ is not derived from ‘const cv::Mat_<_Tp>’
  p2 /= subSample;
     ^
It seems like this operator is not overloaded in Point class. If it's working for you, is it possible to have any issue with version of opencv I am using?

Could you please help me understand this?

Regards,
Nilofer

**Comment by derzu** [comment]
Hi Nilofer,

Maybe is same compiler version difference. Plase replace the flowing line:
`p1 /= subSample;`

to:
`p1.x /= subSample;`
`p1.y /= subSample;`

or:
`p1.x = p1.x/subSample;`
`p1.y = p1.y/subSample;`

I think this should work.

Best regards,

Derzu.

**Comment by niloferbano** [comment]
Thanks, The compiler errors have been fixed.
