### ISSUE TITLE
compile BodySkeletonTracker for webcam

### ISSUE THREAD

**Issue by linzheming** [derzu/BodySkeletonTracker#4]
Hey Derzu,
We wanted to run the code for webcam, so I  comment out this line in Makefile。
`#CFLAGS += -DDEPTH`

It was compiled successfully. But when I tried to run BodySkeletonTracker , I got the following error:

```
james@james-virtual-machine:~/BodySkeletonTracker/Bin/x64-Release$ ./BodySkeletonTracker 
main::Compilado SEM Depth
Compilado SEM Depth
select timeout
select timeout
OpenCV Error: Assertion failed (total() == 0 || data != __null) in Mat, file /home/james/opencv/modules/core/include/opencv2/core/mat.inl.hpp, line 500
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/james/opencv/modules/core/include/opencv2/core/mat.inl.hpp:500: error: (-215) total() == 0 || data != __null in function Mat

Aborted (core dumped)
```

Could you please help me understand this?

Regards,
james

**Comment by derzu** [comment]
Hi Linzheming,

Did you tried to compile with the original Makefile? If so, use the file Makefile.noDepth.

You can simply replace the files doing:

    mv Makefile.noDepth Makefile

Please try that and give me a feedback.

Best regards,

Derzu.

**Comment by linzheming** [comment]
Hey Derzu,
    After changeing a webcam, it's works.  Thank you for your reply.
